/*
* Generated file
*
* Generated from: yang module name: kitchen-service-impl yang module local name: kitchen-service-impl
* Generated by: com.att.opnfv.yang.gradle.JMXGenerator
* Generated at: Wed Apr 08 08:45:40 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.kitchen_service.impl;
public class KitchenServiceModuleFactory extends org.opendaylight.controller.config.yang.config.kitchen_service.impl.AbstractKitchenServiceModuleFactory {

}
