/*
* Generated file
*
* Generated from: yang module name: clustering-it-provider yang module local name: clustering-it-provider
* Generated by: com.att.opnfv.yang.gradle.JMXGenerator
* Generated at: Wed Apr 08 14:43:57 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.clustering_it_provider;
public class ClusteringItProviderModuleFactory extends org.opendaylight.controller.config.yang.config.clustering_it_provider.AbstractClusteringItProviderModuleFactory {

}
