/*
* Generated file
*
* Generated from: yang module name: toaster-provider-impl yang module local name: toaster-provider-impl
* Generated by: com.att.opnfv.yang.gradle.JMXGenerator
* Generated at: Wed Apr 08 08:45:42 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.toaster_provider.impl;
public class ToasterProviderModuleFactory extends org.opendaylight.controller.config.yang.config.toaster_provider.impl.AbstractToasterProviderModuleFactory {

}
